### ISSUE TITLE
Container crashing on startup

### ISSUE THREAD

**Issue by Tiboriuss** [Typhonragewind/meshcentral-docker#11]
Hi,

my latest non MongoDB container is crashing on startup:

node[7]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion (0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0x7fbd4840b3cc node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]

 2: 0x7fbd4840b45b  [/lib/x86_64-linux-gnu/libnode.so.72]

 3: 0x7fbd4848dde2 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/lib/x86_64-linux-gnu/libnode.so.72]

 4: 0x7fbd4848df16 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/lib/x86_64-linux-gnu/libnode.so.72]

 5: 0x7fbd483d62c8 node::InitializeOncePerProcess(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]

 6: 0x7fbd483d64ac node::Start(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]

 7: 0x7fbd47944d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7fbd47944e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0x55dc1536d0f5 _start [node]

/opt/meshcentral/startup.sh: line 28:     7 Aborted                 (core dumped) node node_modules/meshcentral

**Comment by Typhonragewind** [comment]
That's a weird error, and it's working fine on my end. Can you give me some more details so I can try to replicate it?
- Did you build the image yourself?
- Your OS
- Maybe a sanitized version of your docker-compose (without your real domains, etc)

**Comment by Typhonragewind** [comment]
The issue is caused by the docker version. Update docker to the latest version and pull the image again. Check #12 for details.
