### ISSUE TITLE
compress image by 50%

### ISSUE THREAD

**Issue by si458** [Typhonragewind/meshcentral-docker#15]
if you change the package from `ubuntu:latest` to `node:slim` and remove the install of node, you compress the size by 50%!

https://github.com/Ylianst/MeshCentral/blob/master/docker/Dockerfile - check my PR here recently 👍 

amazing image btw!

**Comment by Typhonragewind** [comment]
Sounds like a great suggestion! I'll rebase it and test when i have some free time.
