### ISSUE TITLE
MeshCentral 1.0.36 errors with "not a function"

### ISSUE THREAD

**Issue by BrianAllred** [Typhonragewind/meshcentral-docker#16]
According to [this](thread), the docker image needs an updated NodeJS.

**Comment by tensor5g** [comment]
I am also getting this error: 
```TypeError: optinalHeader.readBigUInt64LE is not a function```

**Comment by Typhonragewind** [comment]
What type (regular or MongoDB) of image are you using ?

**Comment by Typhonragewind** [comment]
Fixed. See #17
