### ISSUE TITLE
Update 1.0.49

### ISSUE THREAD

**Issue by blaine07** [Typhonragewind/meshcentral-docker#19]
Updated container to "latest"/1.0.49 and now browsing to Meshcentral in browser just results in "Unable to connect web socket, click to reconnect."

Not sure what other troubleshooting I can do to be useful.

Also, NO idea why, I just use stuff LOL but rolling back to 1.0.45 seemed to fix it? Or maybe something with Chrome browswer because I ended up having to open it with 1.0.45 to get it to work...So either issue is 1.0.48 or it specifically has an issue with Chrome Browser?

**Comment by Typhonragewind** [comment]
Can you get me the logs while it's failing to reconnect, please?

**Comment by blaine07** [comment]
Pardon my stupidity: I would be happy to get you logs if you can be as kind to point me at which file you need? It’s running as a container in Unraid if it changes anything.

**Comment by Typhonragewind** [comment]
No worries! If you have access to the commandline (i don't know how Unraid works) you can do "docker logs meshcentral" (where meshcentral is your container name)

**Comment by blaine07** [comment]
![Uploading 40A4A469-0D44-44FE-9078-9DCDFF816AF6.jpeg…]()

this?

**Comment by Typhonragewind** [comment]
The link is broken, doesn't send to any picture. If you can copy the text output and paste into a pastebin like this https://pastebin.com/ and share the link

**Comment by blaine07** [comment]
> No worries! If you have access to the commandline (i don't know how Unraid works) you can do "docker logs meshcentral" (where meshcentral is your container name)

Let me get to in morning-ish and I’ll reply back. I did end up moving back to “latest” too. It appears at moment it’s working fine everywhere… other than chrome browser on my Mac. I want to reboot all it tomorrow too though. 🤔🫣

**Comment by blaine07** [comment]
> The link is broken, doesn't send to any picture. If you can copy the text output and paste into a pastebin like this https://pastebin.com/ and share the link

Nothing jumps out as relevant. It's still working in other browsers in other places mostly.. I don't understand.
[
](https://pastebin.com/B9wWXXjK)

**Comment by Typhonragewind** [comment]
That is indeed weird. Have you tried completely cleaning the browser cache on the affected  browser ?

**Comment by blaine07** [comment]
https://github.com/Ylianst/MeshCentral/issues/4242

**Comment by Typhonragewind** [comment]
Aha, so it was more complicated than i thought. Thanks for letting me know, I'll trigger a new build for the updated version.
