### ISSUE TITLE
Backups restore to wrong area.

### ISSUE THREAD

**Issue by 82280zx** [Typhonragewind/meshcentral-docker#24]
When backups are restored they overwrite meshcentral-data, with the current way docker is setup it will make another folder called meshcentral-data inside of the data folder and the backup doesn't restore. Also might want to add /opt/meshcentral/meshcentral-backups :) mesh does auto backups to that folder if you want to download them or back them up.

**Comment by Typhonragewind** [comment]
I'll look into this, I never used meshcentral's own backups so I wasn't aware of these particularities.

thanks for letting me know!

**Comment by Typhonragewind** [comment]
Done! (For regular version at least)
