### ISSUE TITLE
Can't see agents MeshCentral behind a GUI Nginx Proxy Manager on Unraid docker

### ISSUE THREAD

**Issue by hiddenpcmaster** [Typhonragewind/meshcentral-docker#26]
Please forgive my ignorance. Ive been trying to set up for weeks now.  (my first ever post on github too!)

Does anyone have this scenario of this docker container running within an Unraid server behind NGINX proxy manager?
I got the container to spin up but am unable to deploy any agents locally or outside my network.

Can I see a sample config.json file on how to setup?  I'm currently getting 502 Bad Gateway error. Humbly seeking any assistance from anyone.

**Comment by archef2000** [comment]
```json
{
  "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "meshcentral.<your-domain>",
    "WANonly": true,
    "_LANonly": false,
    "sessionKey": "<your-secret>",
    "port": 80,
    "aliasPort": 443,
    "redirPort": 800,
    "TLSOffload": true,
    "WebRTC": true,
    "_redirAliasPort": 800
  },
  "domains": {
    "": {
      "title": "Remote",
      "__title2": "Servername",
      "minify": true,
      "newAccounts": false,
      "userNameIsEmail": false,
      "certUrl": "https://meshcentral.<your-domain>/"
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "myemail@mydomain.com",
    "names": "myserver.mydomain.com",
    "production": false
  }
}

```
This is a config file for a reverse proxy point your NPM to ip of the conatiner and port 80 the url you export meshcentral to must match with `certUrl` or you are gonna get a `Agent bad web cert hash` the meshcentral web portal MUST be accessible without a subpath and without any other AUTH (test with incognito)
