### ISSUE TITLE
 Unable to install required module "otplib@10.2.3"

### ISSUE THREAD

**Issue by Jogai** [Typhonragewind/meshcentral-docker#27]
When trying the normal docker compose I get:
   
```
Installing otplib@10.2.3...

ERROR: Unable to install required module "otplib@10.2.3". MeshCentral may not have access to npm, or npm may not have suffisent rights to load the new module. To manualy install this module try:
```

**Comment by Typhonragewind** [comment]
With these docker images, you shouldn't use the in app upgrade process as that can break stuff. Just pull the new image and recreate the container and it should work fine

**Comment by RoBo-OnGitHub** [comment]
Hello Typhonragewind, 
I might have not expressed myself properly. I didn't do any in-image upgrade. I just pulled the latest version when I've stated to 'upgrade'. I don't remember though if in the previous image I've also already installed the otplib though, so maybe I should not have stated anything about an upgrade. 
Thanks for looking into the issue.

**Comment by RoBo-OnGitHub** [comment]
For me it's 
CentOS Linux release 7.9.2009 (Core); Linux 3.10.0-1160.90.1.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux;
Docker version 24.0.2, build cb74dfc; docker-compose version 1.29.2, build 5becea4c;  typhonragewind/meshcentral:latest

**Comment by Typhonragewind** [comment]
Can't for the life of me replicate this issue on my end

**Comment by Typhonragewind** [comment]
I have pushed an imaged that may fix this issue by preloading the necessary libs, Could you please try using the tag typhonragewind/meshcentral:preloadlib ?

**Comment by Typhonragewind** [comment]
Awesome! As soon as i finish up some other changes i'll push this to the main branch

**Comment by RoBo-OnGitHub** [comment]
Thanks.. pulled latest and all is okay now. Thanks for your support!

**Comment by ra3ggi** [comment]
Опять подобная проблема и тег "preloadlib:latest" не помогает.
