### ISSUE TITLE
Publish ARM image

### ISSUE THREAD

**Issue by LilDrunkenSmurf** [Typhonragewind/meshcentral-docker#29]
Hi there, considering that the meshcentral documentation specifies the ability to run this on something like an RPi, I was wondering if you were considering building an ARM image.

After cloning the repo, I was able to build and run an image from your existing dockerfile with no issues.

**Comment by LilDrunkenSmurf** [comment]
Docker lets you build for other architectures using the `buildx` command: https://docs.docker.com/engine/reference/commandline/buildx_build/

Additionally, you could use github actions to automatically build it, and host it on github instead of the docker repo, similar to this:
https://github.com/onedr0p/containers/blob/main/.github/workflows/action-image-build.yaml

**Comment by Typhonragewind** [comment]
Multiarch images implemented (with github actions).

Thank you for the suggestion!
