### ISSUE TITLE
Unclear on the format of ENV variables

### ISSUE THREAD

**Issue by maxcerny** [Typhonragewind/meshcentral-docker#34]
I'm currently trying to install this container, with mongo.

Using the dockerfile provided, and setting the variables as such

```
 environment:
            - HOSTNAME=https://mesh.ogresearch.com:443     #your hostname
            - REVERSE_PROXY=false    #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
            - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=false #set to true if you wish to enable iframe support
            - ALLOW_NEW_ACCOUNTS=true    #set to false if you want disable self-service creation of new accounts besides the first (admin)
            - WEBRTC=false  #set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
            - NODE_ENV=production
```

results in a wrongly generated config.json

My issue is that there is no proper documentation on the format these variables are supposed to be in. 

Is HOSTNAME mesh.ogresearch.com, https://mesh.ogresearch.com, or https://mesh.ogresearch.com?

The same goes for the proxy, is it the IP of the proxy itself, from the side of mesh central (in my case caddy in another docker), or the IP of the resolved hostname?

If you could clear those up for me, that ould be very helpful, and maybe add them to the docs.

**Comment by maxcerny** [comment]
In the end I figured it out, with the help of docs from ibracorp...
https://docs.ibracorp.io/meshcentral/#install-meshcentral
I do still think that making the docs here more verbose would be a good idea.

**Comment by Typhonragewind** [comment]
I do link to all the docs available for Meshcentral (directly from its Dev).
I'd rather not research and rewrite documentation for each specific use case -  for example, I don't use Caddy and have no idea how it works
