### ISSUE TITLE
"Installing ua-parser-js@1.0.35..." 

### ISSUE THREAD

**Issue by ra3ggi** [Typhonragewind/meshcentral-docker#37]
Meshcentral was installed from 
https://hub.docker.com/r/typhonragewind/meshcentral on TrueNAS Scale 
Everything has been working for over three months.
After a recent update, there is an endless error - "Installing ua-parser-js@1.0.35..." 
https://i.imgur.com/GgiXyxa.png
Specifying "preloadlibs-latest" does not solve the problem.
Please help

**Comment by ra3ggi** [comment]
Maybe this will help: 
"In version 18.17.1, the path to nodejs has changed.
Note: the node command change location and the old location may be remembered in your current shell.
old : /usr/bin/node
new : /usr/local/bin/node"

**Comment by Typhonragewind** [comment]
I'll look into this, thanks for all the debugging!

**Comment by ra3ggi** [comment]
At the moment everything is working !

**Comment by ra3ggi** [comment]
Strangely, I don't have a problem with "otplib@10.2.3". although my tag is not preloadlibs-latest but latest

**Comment by ra3ggi** [comment]
With the latest update and I have a problem with endless "Installing otplib@10.2.3..."
Installing "preloadlibs-latest" doesn't work
I can't enter the commands for manual installation, because it is installed on TrueNAS, and there it has its own specifics. 
Help, please :)

**Comment by ra3ggi** [comment]
Honestly, I got tired of the problems with this docker and switched to another ( https://hub.docker.com/r/vegardit/meshcentral ), which I advise everyone to do. There are no problems there and everything is updated in a timely manner.
