### ISSUE TITLE
Image now broken?

### ISSUE THREAD

**Issue by kanintesova** [Typhonragewind/meshcentral-docker#38]
I get this in the logs:

```
Error: Cannot find module '/opt/meshcentral/node_modules/meshcentral'

    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)

    at Module._load (node:internal/modules/cjs/loader:922:27)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)

    at node:internal/main/run_main_module:23:47 {

  code: 'MODULE_NOT_FOUND',

  requireStack: []

}

```
Ok I missed the first lines of the log. Will try the preloadlibs image.

Nope, get the same errors. I have not changed anything so it is super weird.

**Comment by zedocrob** [comment]
Same problem here with "latest" or "preloadlibs-latest"

**Comment by kanintesova** [comment]
Have you tried any prior image? I tried a few versions back and it did not work. Then tried the latest preloadlib but no luck so gave up.

It is weird because it was up and running. Then I did a repull because I had some problems with a new reverse proxy. Then this started to happen. Even tried fresh and let it repopulate all the bind mount folders. It only generates one json file then quits with this error.

But can not get my head around why any older image works, because I set it up like 3 weeks ago.

**Comment by zedocrob** [comment]
Also tried to roll back to previous image too and same problem, don't know what happened...

**Comment by kanintesova** [comment]
I suspect/think the container is fetching some package from npm install, but that this is maybe now broken somehow. I can be wrong.

It is not able to install the archiver utily as well.

Bummer.

**Comment by kanintesova** [comment]
Thanks ❤️

**Comment by Typhonragewind** [comment]
> @Typhonragewind Is the upgrade process to a newer meshcentral version very involved? Perhaps we could submit pull requests to get this done in the future to reduce the pressure on you to release every version so quickly?

Thanks for the offer, but the process is mostly automated (unless something breaks). This time the issue was actually upstream on Meshcentral installation itself

**Comment by Typhonragewind** [comment]
It should be fixed now
