### ISSUE TITLE
Agent Port

### ISSUE THREAD

**Issue by neobiotics** [Typhonragewind/meshcentral-docker#5]
Sorry for maybe having a beginner question which also may be out of place here but - how do I make the linux agent connect to the server at the port I defined in the docker-compose file? My google-fu doesnt get me anywhere with this...

TIA
J

**Comment by Typhonragewind** [comment]
No problem at all! 
The thing is, if you have configured Meshcentral correctly in the server, the client should connect automatically, as it downloads all the necessary settings from the server.

Check the client logs and to which IP:PORT it is trying to connect.

**Comment by neobiotics** [comment]
It does try to connect to 443, which seems logical because in my docker-compose file I do
`ports:
            - 8086:443`
I think I have to configure port 8086 in the config.json and do "8086:8086" in the compose file?

again
TIA

**Comment by Typhonragewind** [comment]
> I think I have to configure port 8086 in the config.json and do "8086:8086" in the compose file?

That shouldn't be needed.

Are you using any sort of proxy or reverse proxy? Are you just connecting through LAN? Did you define certs for the https?
