### ISSUE TITLE
NodeJS version - Unable to SSH using local groups.

### ISSUE THREAD

**Issue by bodycount28** [Typhonragewind/meshcentral-docker#6]
I'm unable to SSH using local group (without agent), error log shows that minimum v11 NodeJS is required.  I believe you got v10.9 installed on the image.  Any plans to upgrade NodeJS?

Thanks for keeping your meshcentral versions up to date!

**Comment by Typhonragewind** [comment]
I'd gladly up the version of it, but the way it is currently done is through the latest pkg from the ubuntu repo. I'm not keen on manually updating it through node itself without testing the docker image stability, which I currently don't have much time for.

If you want, I can create a dev image with the updated node tonight and you could test and report back though 😄

**Comment by bodycount28** [comment]
Because of this limitation I tried using another image and that worked without issue.  However, if you decide to create a dev image, I'd be happy to test out for you and report back the results.
